/**
 * SEC-GEPA-05 — no hot-swap activation resolver (T13, runtime test).
 *
 * An evolved skill is NEVER swapped into a live session (SEC-GEPA-05 /
 * T10 §2 "hot-swap"). Activation is only allowed BETWEEN sessions, after
 * merge + human approval (T10 §7.1 D-9). The runtime resolver therefore
 * reads **merged registry state only**:
 *
 *   - `resolveActivation(state, skill, sha256)` — allowed iff the exact
 *     file hash is present in the merged registry state (a record with
 *     `source: 'merged'` written from the merged `develop` branch).
 *   - A candidate that exists ONLY on an `evolution/<skill>/...` branch
 *     or in `evolution/runs/**` artifacts has no merged record → the
 *     resolver REFUSES activation (R-6 hot-swap attempt).
 *   - Missing / empty registry state is fail-closed: nothing activates.
 *
 * The registry state file (`<registryDir>/registry-state.json`) is a
 * derived artifact of the merged branch — regenerated by the workflow's
 * `registry-state` command (or CI on develop) AFTER a human merge. It is
 * the ONLY input the resolver accepts: run manifests and candidate
 * branches are structurally rejected (see `assertRegistryState`).
 */

import { readFileSync } from 'node:fs';

export interface MergedSkillRecord {
    skill: string;
    /** sha256 of the merged SKILL.md file. */
    sha256: string;
    source: 'merged';
    merged_at: string;
    pr_url: string | null;
}

/** The merged registry state — the ONLY activation input (SEC-GEPA-05). */
export interface RegistryState {
    schema_version: 1;
    built_from: string;
    skills: Record<string, MergedSkillRecord>;
}

export interface ActivationDecision {
    allowed: boolean;
    reason: string;
}

/** Fail-closed: a missing/empty state activates nothing. */
export function emptyRegistryState(builtFrom: string): RegistryState {
    return { schema_version: 1, built_from: builtFrom, skills: {} };
}

/**
 * Structural guard: the resolver only accepts a `RegistryState` object
 * (merged registry state). Passing a run manifest, a candidate record or
 * a run-artifact path is a hot-swap attempt and is refused (R-6).
 */
export function assertRegistryState(value: unknown): asserts value is RegistryState {
    if (
        typeof value !== 'object' ||
        value === null ||
        (value as { schema_version?: unknown }).schema_version !== 1 ||
        typeof (value as { built_from?: unknown }).built_from !== 'string' ||
        typeof (value as { skills?: unknown }).skills !== 'object' ||
        (value as { skills?: unknown }).skills === null
    ) {
        throw new Error(
            'SEC-GEPA-05: activation input is not the merged registry state — ' +
                'activation reads merged registry state only; run manifests/candidates are not activation inputs',
        );
    }
}

/**
 * Resolve activation for `skill` at file hash `sha256` against the
 * merged registry state. Allowed ONLY when the exact merged file matches.
 */
export function resolveActivation(state: RegistryState, skill: string, sha256: string): ActivationDecision {
    const record = state.skills[skill];
    if (!record) {
        return {
            allowed: false,
            reason: `SEC-GEPA-05: skill '${skill}' has no merged registry record — ` +
                'activation only between sessions, after merge + human approval (D-9); nothing to activate',
        };
    }
    if (record.source !== 'merged') {
        return {
            allowed: false,
            reason: `SEC-GEPA-05: skill '${skill}' record is not from the merged registry state (source=${record.source})`,
        };
    }
    if (record.sha256 !== sha256) {
        return {
            allowed: false,
            reason:
                `SEC-GEPA-05: candidate sha256 ${sha256.slice(0, 12)}… does not match the merged ` +
                `registry record ${record.sha256.slice(0, 12)}… for '${skill}' — the candidate is NOT merged; ` +
                'activation only after merge + human approval (R-6 hot-swap attempt)',
        };
    }
    return {
        allowed: true,
        reason:
            `SEC-GEPA-05: candidate sha256 ${sha256.slice(0, 12)}… for '${skill}' matches the merged ` +
            `registry record (merged_at=${record.merged_at}, pr=${record.pr_url ?? 'n/a'}) — ` +
            'activation allowed only between sessions',
    };
}

/** CLI: `... activation <state.json> <skill> <sha256>` — exit 0 iff allowed. */
export function activationCli(statePath: string, skill: string, sha256: string): number {
    const state = JSON.parse(readFileSync(statePath, 'utf8')) as unknown;
    assertRegistryState(state);
    const d = resolveActivation(state, skill, sha256);
    // eslint-disable-next-line no-console
    console.log(`SEC-GEPA-05 activation check: ${d.allowed ? 'ALLOWED' : 'REFUSED'} — ${d.reason}`);
    return d.allowed ? 0 : 1;
}
